/** @type {import('@commitlint/types').UserConfig} */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'subject-case': [2, 'always', ['lower-case']],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'body-leading-blank': [2, 'always'],
    'footer-leading-blank': [2, 'always'],
    'header-max-length': [2, 'always', 100],
  },
  prompt: {
    settings: {
      scopeEnum: [
        'api',
        'dashboard',
        'core',
        'shared',
        'runtime',
        'workflow',
        'agents',
        'memory',
        'event-bus',
        'adapters',
        'adapters-sdk',
        'observability',
        'ui',
        'hermes',
        'ci',
        'deploy',
        'deps',
        'release',
      ],
    },
  },
};
